// AUTO-GENERATED by `cortextos ecosystem`. Do NOT edit by hand.
// Re-run `cortextos ecosystem` to regenerate.
//
// Note: env vars use process.env.X || 'default' so PM2 picks up the value
// from the calling shell at startup time. This means `CTX_INSTANCE_ID=foo
// pm2 restart cortextos-daemon` switches instances without regenerating.
module.exports = {
  apps: [
    {
      name: 'cortextos-daemon',
      script: "/home/bones/cortextos/dist/daemon.js",
      args: '--instance ' + (process.env.CTX_INSTANCE_ID || "default"),
      cwd: "/home/bones/cortextos",
      env: {
        CTX_INSTANCE_ID: process.env.CTX_INSTANCE_ID || "default",
        CTX_ROOT: process.env.CTX_ROOT || "/home/bones/.cortextos/default",
        CTX_FRAMEWORK_ROOT: "/home/bones/cortextos",
        CTX_PROJECT_ROOT: "/home/bones/cortextos",
        CTX_ORG: process.env.CTX_ORG || "vault",
        // Operator alert channel (PLAN-v3 §10). NOT a secret — it names the
        // agent whose own .env supplies BOT_TOKEN + CHAT_ID, so it is safe in
        // this git-tracked generated file. Emitted HERE rather than hand-added
        // to the output: this generator writes a FIXED env list, so anything
        // added by hand is silently dropped on the next regeneration
        // run — and the operator channel would go dark with nothing saying so.
        CTX_OPERATOR_AGENT: process.env.CTX_OPERATOR_AGENT || "solo",
        // On by default. global fetch (Undici) hardcodes autoSelectFamily=false
        // and wedges on broken-dual-stack hosts (IPv6 configured but blackholed)
        // by committing to the dead family for the full timeout. Routing the
        // Telegram JSON API calls and file downloads over a dedicated keep-alive
        // node:https path gives us Happy Eyeballs (autoSelectFamily) instead,
        // which races the families and self-heals, without breaking IPv6-only
        // hosts (multipart photo/document uploads stay on pooled fetch). Set to
        // '0' to opt out and force pooled fetch.
        CORTEXTOS_TELEGRAM_UNPOOLED_HTTPS: process.env.CORTEXTOS_TELEGRAM_UNPOOLED_HTTPS || '1',
        // Debug-only: set to '1' to enable SIGUSR2 signal → controlled
        // uncaughtException for testing the crash-visibility path
        // (.daemon-crashed markers + crash-loop operator Telegram alert).
        // Leave '0' in production; enable temporarily to reproduce crash
        // paths during development. `kill -SIGUSR2 $(pm2 pid cortextos-daemon)`
        // then watch the operator chat for "🚨 CRITICAL: daemon crash-looping"
        // after 3 crashes in 15 min.
        CTX_DEBUG_ALLOW_CRASH_TRIGGER: '0',
      },
      // max_restarts + restart_delay is the ultimate crash-storm circuit
      // breaker. If the daemon dies 10 times faster than 5s apart, PM2
      // gives up — the fleet goes fully dead, requiring a manual
      // `pm2 restart cortextos-daemon`. That is intentional: storm
      // protection > fleet uptime during a pathological crash loop.
      // The daemon's uncaughtException handler (src/daemon/index.ts)
      // fires a Telegram alert to the operator at 3+ crashes in 15 min —
      // well before this circuit trips. Do NOT raise these values without
      // also strengthening the upstream fix; the 2026-04-22 storm is a
      // reminder that unchecked auto-restart amplifies one bug into a
      // fleet-wide outage.
      max_restarts: 10,
      restart_delay: 5000,
      autorestart: true,
    },
    {
      name: 'cortextos-dashboard',
      script: "npm",
      args: "run dev",
      cwd: "/home/bones/cortextos/dashboard",
      env: {
        PORT: process.env.PORT || '3000',
      },
      // Dashboard reads its real config from dashboard/.env.local — populated
      // by /onboarding Phase 7. PM2 just supervises the dashboard process.
      windowsHide: true,
      max_restarts: 50,
      restart_delay: 5000,
      autorestart: true,
    },
  ],
};
