// AUTO-GENERATED by `cortextos ecosystem`. Do NOT edit by hand.
// Re-run `cortextos ecosystem` to regenerate.
//
// Note: env vars use process.env.X || 'default' so PM2 picks up the value
// from the calling shell at startup time. This means `CTX_INSTANCE_ID=foo
// pm2 restart cortextos-daemon` switches instances without regenerating.
module.exports = {
  apps: [
    {
      name: 'cortextos-daemon',
      script: "/home/bones/cortextos/dist/daemon.js",
      args: '--instance ' + (process.env.CTX_INSTANCE_ID || "default"),
      cwd: "/home/bones/cortextos",
      env: {
        CTX_INSTANCE_ID: process.env.CTX_INSTANCE_ID || "default",
        CTX_ROOT: process.env.CTX_ROOT || "/home/bones/.cortextos/default",
        CTX_FRAMEWORK_ROOT: "/home/bones/cortextos",
        CTX_PROJECT_ROOT: "/home/bones/cortextos",
        CTX_ORG: process.env.CTX_ORG || "vault",
        // Operator alert channel (PLAN-v3 §10). NOT a secret — it names the
        // agent whose own .env supplies BOT_TOKEN + CHAT_ID, so it is safe in
        // this git-tracked generated file. Emitted HERE rather than hand-added
        // to the output: this generator writes a FIXED env list, so anything
        // added by hand is silently dropped on the next regeneration
        // run — and the operator channel would go dark with nothing saying so.
        CTX_OPERATOR_AGENT: process.env.CTX_OPERATOR_AGENT || "solo",
      },
      max_restarts: 50,
      restart_delay: 5000,
      autorestart: true,
    },
    {
      name: 'cortextos-dashboard',
      script: "npm",
      args: "run dev",
      cwd: "/home/bones/cortextos/dashboard",
      env: {
        PORT: process.env.PORT || '3000',
      },
      // Dashboard reads its real config from dashboard/.env.local — populated
      // by /onboarding Phase 7. PM2 just supervises the dashboard process.
      windowsHide: true,
      max_restarts: 50,
      restart_delay: 5000,
      autorestart: true,
    },
  ],
};
